### ISSUE TITLE
No outputs of scan result

### ISSUE THREAD

**Issue by Wivik** [SonarSource/sonarqube-quality-gate-action#21]
Hello,
I've setup this action after a Sonarscanner step, providing the metadata file, the Quaity Gate action displays the result.

But I want to use this result to abort the pipeline if the quality gates have failed, but the outputs are empty.

Here is my pipeline : 

```yaml
      - name: Sonar
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ./front

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-result-front
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: ./front/.scannerwork/report-task.txt

      - name: "Display Quality gate result"
        run: echo "Front Quality Gate status ${{ toJSON(steps.sonarqube-result-front) }}"
       ## ${{ steps.sonarqube-result-front.outputs.quality-gate-status }} is NULL
```

I've run the pipeline with Debug steps and displayed the Quality Gates check action output with the toJSON expression to see what's inside, and the outputs are empty.

![image](https://user-images.githubusercontent.com/48727868/185571511-3070f350-5581-4b82-baa0-d03866f0e384.png)

I can't see what's wrong, everything is made according to the documentation or I've missed something ?

Thanks for your help !

**Comment by LeonardoZV** [comment]
Yeah same thing here.

**Comment by Wivik** [comment]
As the Action is calling Sonarqube's API by reading the job manifest, I've tried myself by creating basic `run` tasks in the pipeline (one that extract the API URL from the manifest, a second calling it with the result as an output) and it works fine. 

Maybe a problem with the GitHub Actions framework and shell scripts based Actions ?

**Comment by remoteexception** [comment]
I've created a Pull Request to fix the missing output: https://github.com/SonarSource/sonarqube-quality-gate-action/pull/22 . It's tested in my sonarqube-quality-gate-action-Fork and works. The PR needs to be approved.

**Comment by Marvin-Brouwer** [comment]
I'm having the same issue, @wouter-admiraal-sonarsource I see you closed the PR but yet the problem still persists.
Do you have any idea how we may help you?

**Comment by Wivik** [comment]
Since this issue I've tried to use directly `run` instead of a separated shell script and it works.

```yaml
name: SonarQube Quality Gate Check
description: >
  Check if a project / analysis passed the Quality Gate check
branding:
  icon: check
  color: green
runs:
  using: "composite"
  steps:
      - name: Get Job Result URL
        id: geturl
        run: echo "::set-output name=url::$(grep 'ceTaskUrl=' ${{ inputs.scanMetadataReportFile }} | sed 's/ceTaskUrl=//')"
        shell: bash

      - name: Get Job result
        id: getjobresult
        run: |
          status=$(curl --silent -u ${{ env.SONAR_TOKEN }}: ${{ steps.geturl.outputs.url }} | jq '.[].status' -r)
          until [[ ${status} != "PENDING" && ${status} != "IN_PROGRESS" ]]; do
            sleep 5
            status=$(curl --silent -u ${{ env.SONAR_TOKEN }}: ${{ steps.geturl.outputs.url }} | jq '.[].status' -r)
            echo "Job status : ${status}"
          done
          analysisid=$(curl --silent -u ${{ env.SONAR_TOKEN }}: ${{ steps.geturl.outputs.url }} | jq '.[].analysisId' -r)
          echo "::set-output name=analysisid::${analysisid}"
        shell: bash

      - name: Get Project status
        id: getprojectstatus
        run: |
          qgstatus=$(curl --silent -u ${{ env.SONAR_TOKEN }}: ${{ env.SONAR_HOST_URL }}api/qualitygates/project_status?analysisId=${{ steps.getjobresult.outputs.analysisid }} |  jq '.projectStatus.status' -r)
          echo "::set-output name=qgstatus::${qgstatus}"
        shell: bash

      - name: Validate result
        shell: bash
        run: |
          echo "SonarQube quality gate result is ${{ steps.getprojectstatus.outputs.qgstatus }}" >> $GITHUB_STEP_SUMMARY
          case "${{ steps.getprojectstatus.outputs.qgstatus }}" in
            OK) echo "::set-output name=quality-gate-status::${{ steps.getprojectstatus.outputs.qgstatus }}" && exit 0 ;;
            WARN) echo "::set-output name=quality-gate-status::${{ steps.getprojectstatus.outputs.qgstatus }}" && exit 1 ;;
            ERROR) echo "::set-output name=quality-gate-status::${{ steps.getprojectstatus.outputs.qgstatus }}" && exit 1 ;;
            *) echo "Quality gate not set for this project." && exit 1 ;;
          esac
inputs:
  scanMetadataReportFile:
    description: Location of the scanner metadata report file
    required: false
    default: .scannerwork/report-task.txt
outputs:
  quality-gate-status:
    description: >
      The resulting Quality Gate Status value of PASSED, WARN or FAILED
```
