### ISSUE TITLE
Quality gate task fails when scanning project with a projectBaseDir set

### ISSUE THREAD

**Issue by jordanchang** [SonarSource/sonarqube-quality-gate-action#42]
Error from quality gate task ".scannerwork/report-task.txt does not exist."

It appears it is not about to find the report file since my scan was performed in the "client" folder of my repo.

    # Triggering SonarQube analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: client
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

**Comment by javiertuya** [comment]
Maybe you need to set `scanMetadataReportFile`  to set the client folder. You can find an example at the last step of `action.yml` at https://github.com/javiertuya/sonarqube-action

**Comment by extravio** [comment]
As @javiertuya mentioned, the following should work:
```
 - name: SonarQube Quality Gate check
    uses: sonarsource/sonarqube-quality-gate-action@master
    [...]
    with:
        scanMetadataReportFile: client/.scannerwork/report-task.txt
```
