### ISSUE TITLE
Quality Gate not set for the project. Please configure the Quality Gate in SonarQube or remove sonarqube-quality-gate action from the workflow.

### ISSUE THREAD

**Issue by akhil-intellect** [SonarSource/sonarqube-quality-gate-action#7]
i am keep on getting this error in al my profile , quality gateway is enabled in my profile 

![Screen Shot 2021-06-28 at 2 38 59 PM](https://user-images.githubusercontent.com/77638938/123687194-a4c62680-d81e-11eb-9ab5-6cf558eb96e0.png)

**Comment by pbrzozowski-equinix** [comment]
I face the same issue. It always falls back to this message. I found out that it happens, because all the Sonar urls in the output file (report-task.txt) produced by my SonarQube have `http://` addresses instead of `https://`. Then sonar have HTTP to HTTPS redirection. 

Curl used in the script of this GitHub Action by default is not supporting redirections. So the script basically is not getting any data. If you can add `--location` flag to all curl executions it would follow HTTP to HTTPS redirection.

Workaround for users might be to edit report-task.txt before using Quality Gate check action. You need to replace all the `http:` occurances to `https:`
Solution that I just used:
```
  - name: Create report-task-https.txt with changed urls
    run:  cat build/sonar/report-task.txt | sed s/http\:/https\:/g > build/sonar/report-task-https.txt
```
Then remember to use `report-task-https.txt` instead of `report-task.txt`. 
More complete example:
```
  - name: Create report-task-https.txt with changed urls
    run:  cat build/sonar/report-task.txt | sed s/http\:/https\:/g > build/sonar/report-task-https.txt
  - name: SonarQube Quality Gate check
    uses: sonarsource/sonarqube-quality-gate-action@master
    timeout-minutes: 5
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      scanMetadataReportFile: build/sonar/report-task-https.txt
```
